service: serverless-chaos-demo-disk

frameworkVersion: ">=1.34.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7
  memorySize: 128
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogStream
        - ssm:DescribeParameters
        - logs:CreateLogGroup
        - logs:PutLogEvents
      Resource: "*"
    - Effect: Allow
      Action:
        - ssm:GetParameters
        - ssm:GetParameter
      Resource: "arn:aws:ssm:${opt:region, self:provider.region}:*:parameter/${self:service}*"

functions:
  diskFunction:
    handler: diskFunction.function
    timeout: 6
    environment:
      FAILURE_INJECTION_PARAM:
        Ref: diskFunctionParameter
    layers:
      - ${file(env.yml):layer}
    events:
      - http:
          path: diskFunction/
          method: get
          cors: true

resources:
  Resources:
    diskFunctionParameter:
      Type: 'AWS::SSM::Parameter'
      Properties:
        Name: ${self:service}-${opt:stage, self:provider.stage}-diskFunction
        Type: String
        Value: ${file(env.yml):failure_conf}
